name: Deploy SimpleMessagingApp

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: create .env file
        run: echo "PORT ${{ secrets.PORT }}" >> .env
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build . -t egardev/simple_messaging_app
      - name: Push docker image to dockerhub
        run: docker push egardev/simple_messaging_app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: docker pull egardev/simple_messaging_app:latest
      - name: Delete old docker container
        run: docker rm -f simple_messaging_app
      - name: Running new docker container
        run: docker run -d -p 8080:8080 -p 4000:4000 --name simple_messaging_app egardev/simple_messaging_app:latest
